package:
    name: eman-deps
    version: '15.1'

build:
    number: 0
    skip: True  # [win32]

requirements:
    run:
        - {{ pin_subpackage('eman-deps-cli', exact=True) }}
        - pyqt           5.*
        - pyopengl       3.1.0

outputs:
  - name: eman-deps-cli
    requirements:
      run:
        - msinttypes                        # [win]
        - python         2.7.14
        - boost          1.63.*
        - fftw-mpi
        - numpy          1.13.*
        - ftgl
        - freetype
        - gsl            2.4.*
        - hdf5           1.8.18
        - jpeg           9b
        - libtiff        4.0.9              # [not win]
        - libtiff        4.0.9  hafacce9_0  # [win]
        - libpng         1.6.34
        - zlib
        - matplotlib
        - scipy          1.*
        - ipython
        - tensorflow-gpu 1.5.*              # [linux]
        - cudatoolkit    8.0.*              # [linux]
        - cudnn          7.0.*              # [linux]
        - tensorflow     1.5.*              # [osx]
        - scikit-learn   0.19.*
        - bsddb                             # [not win]
        - openmpi        2.0.2              # [not win]
        - pydusa                            # [not win]
        - nose
        - future
        - configparser
        - tqdm
        - libcxx         4.0.1  h579ed51_0  # [osx]

      run_constrained:
        - cmake          3.14.*
        - conda          4.6.14
        - conda-build    3.17.8

about:
  summary: Meta-package for eman2 dependencies
