{% set build  = 2 %}
{% set openmpi_ver  = 3 %}

package:
    name: eman-deps
    version: '16.0'

build:
    number: {{ build }}
    string: openmpi{{ openmpi_ver }}_{{ build }}  # [not win]
    skip: True  # [win32]

requirements:
    run:
        - pyqt           5.*
        - pyopengl       3.1.0
        - msinttypes                        # [win]
        - python         2.7.*
        - boost
        - fftw           3.3.8  nompi_*     # [win]
        - numpy          1.13.*
        - ftgl
        - freetype
        - gsl            2.4.*
        - hdf5           1.8.18
        - jpeg           9b
        - libtiff        4.0.9              # [not win]
        - libtiff        4.0.9  hafacce9_0  # [win]
        - libpng         1.6.37
        - zlib
        - matplotlib
        - scipy          1.*
        - ipython
        - scikit-learn   0.19.*
        - bsddb                             # [not win]
        - pydusa         1.15 openmpi{{ openmpi_ver }}_13          # [not win]
        - nose
        - future
        - configparser
        - tqdm

    run_constrained:
        - cmake          3.14.*
        - conda          4.6.14
        - conda-build    3.17.8

about:
  summary: Meta-package for eman2 dependencies
