{% set build  = 2 %}
{% set openmpi_ver  = 3 %}

package:
    name: eman-deps
    version: '16.0'

build:
    number: {{ build }}
    string: openmpi{{ openmpi_ver }}_{{ build }}  # [not win]
    skip: True  # [win32]

requirements:
    run:
        - pyqt           5.*
        - pyopengl       3.1.0
        - python         3.6.*
        - boost
        - fftw           3.3.8  nompi_*     # [win]
        - numpy          1.13.*
        - ftgl
        - freetype
        - gsl            2.4.*
        - hdf5           1.8.18
        - jpeg
        - libtiff        4.0.9
        - libpng         1.6.37
        - zlib
        - matplotlib    >3.0.0
        - scipy          1.*
        - ipython
        - scikit-learn   0.19.*
        - bsddb3                            # [not win]
        - pydusa         1.15 openmpi{{ openmpi_ver }}_14          # [not win]
        - nose
        - future
        - configparser
        - tqdm

    run_constrained:
        - cmake          3.14.*
        - conda          4.6.14
        - conda-build    3.17.8

about:
  summary: Meta-package for eman2 dependencies
