{% set numpy_ver  = 1.17 %}

package:
    name: eman-deps-dev
    version: '20.0'

build:
    number: 0
    skip: True  # [win32]

requirements:
    run:
        - cmake          3.14.*
        - pyqt           5.*
        - pyopengl       3.1.5
        - matplotlib    >3.0.0
        - scipy          1.*
        - ipython
        - scikit-learn
        - bsddb3                            # [not win]
        - pydusa         1.15 numpy{{ numpy_ver }}_15   # [not win]
        - nose
        - future
        - configparser
        - tqdm
        - python         3.7.*
        - boost          1.69.*                # [not linux]
        - boost          1.69.* *_0            # [linux]
        - boost-cpp      1.69.* *_0            # [linux]
        - fftw           3.3.8  mpi_openmpi_*  # [not win]
        - fftw           3.3.8  nompi_*        # [win]
        - numpy          {{ numpy_ver }}
        - ftgl           2.4.0
        - freetype
        - gsl            2.4.*
        - hdf5           1.8.18
        - jpeg
        - libtiff        4.0.9
        - libpng         1.6.37
        - zlib

about:
  summary: Meta-package for eman2 dependencies
