package:
    name: eman-deps
    version: '1.0'

build:
    number: 1
    skip: True  # [win32]

requirements:
    {% set reqs_common = [
            "python 2.7.*",
            "boost 1.61.*",
            "fftw-mpi",
            "numpy x.x",
            "ftgl",
            "freetype",
            "gsl",
            "hdf5",
            "jpeg",
            "libgfortran 1.0",  # [linux]
            "libgfortran",      # [osx]
            "libtiff",
            "libpng >=1.6.*",
            "zlib",
            "szip",  # [win]
            "bsddb",  # [not win]
            "matplotlib",
            "ipython",
            "pyqt 4.*",
            "pyopengl 3.1.0",
            "theano",
            "scikit-learn",
            "pydusa",  # [not win]
            "msinttypes",  # [win]
            "szip",  # [win]
            "cmake"
    ] %}
    
    build:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
    
    run:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}

about:
  summary: Meta-package for eman2 dependencies
