package:
    name: eman-deps
    version: '4.0'

build:
    number: 0

requirements:
    {% set reqs_common = [
            "python 2.7.*",
            "boost 1.63.*",
            "fftw-mpi",   # [not win]
            "fftw",       # [win]
            "numpy x.x",  # [not win]
            "numpy",      # [win]
            "libgfortran 1.*",  # [np<19 and linux]
            "ftgl",
            "freetype",
            "gsl",
            "hdf5",
            "jpeg",
            "libtiff",
            "libpng",
            "zlib",
            "bsddb",  # [not win]
            "matplotlib",
            "ipython",
            "pyqt 4.*",
            "pyopengl 3.1.0",
            "theano",
            "scikit-learn",
            "openmpi",  # [not win]
            "pydusa",  # [not win]
            "msinttypes",  # [win]
            "cmake >=3.8.*"
    ] %}
    
    build:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
    
    run:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}

about:
  summary: Meta-package for eman2 dependencies
