package:
    name: eman-deps
    version: '14.0'

build:
    number: 0
    skip: True  # [win32]

requirements:
    {% set reqs_common = [
            "msinttypes",  # [win]
            "python 2.7.14",
            "boost 1.63.*",
            "fftw-mpi",
            "numpy 1.13.*",
            "ftgl",
            "freetype ",
            "gsl",
            "hdf5 1.8.18",
            "jpeg",
            "libtiff 4.0.9",             # [not win]
            "libtiff 4.0.9 hafacce9_0",  # [win]
            "libpng 1.6.34",
            "zlib",
            "matplotlib",
            "scipy 1.*",
            "ipython",
            "pyqt 5.*",
            "pyopengl 3.1.0",
            "scikit-learn 0.19.*",
            "bsddb",          # [not win]
            "openmpi 2.0.2",  # [not win]
            "pydusa",         # [not win]
            "nose",
            "future",
            "configparser",
            "tqdm",
    ] %}
    
    run:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}

about:
  summary: Meta-package for eman2 dependencies
