{% set build  = 1 %}

package:
    name: eman-deps-dev
    version: '18.1'

build:
    number: {{ build }}
    string: numpy{{ numpy }}_{{ build }}
    skip: True  # [win32]

requirements:
    run:
      - cmake            3.14.*
      - pyqt           5.*
      - pyopengl       3.1.5
      - python         3.7.*
      - boost        >=1.68
      - fftw           3.3.8  nompi_*     # [win]
      - numpy          {{ numpy }}
      - ftgl
      - freetype
      - gsl            2.4.*
      - hdf5           1.8.18
      - jpeg
      - libtiff        4.0.9
      - libpng         1.6.37
      - zlib
      - matplotlib    >3.0.0
      - scipy          1.*
      - ipython
      - scikit-learn
      - tensorflow-gpu 1.5.*              # [linux]
      - cudatoolkit    8.0.*              # [linux]
      - cudnn          7.0.*              # [linux]
      - tensorflow     1.5.*              # [osx]
      - bsddb3                            # [not win]
      - pydusa         1.15 numpy{{ numpy }}_15   # [not win]
      - nose
      - future
      - configparser
      - tqdm

    run_constrained:
      - cmake          3.14.*
      - conda          4.6.14
      - conda-build    3.17.8

about:
  summary: Meta-package for eman2 dependencies
