travis:
  secure:
    BINSTAR_TOKEN: FWQ2CDvdipryWN2WN7U4h6Wuvd1L2KPo4oBy8bzZu2hQOpclJlX60WwYCUIXmPuKHDTd8dhal/TgbmVmjKhIo+KynnPuM8mJALBfXcumoCDUK/RUn9b+GgZsuz289hpDmJNifSYvuViQ8W/leUZ5PAq3xXLePDihmi0gdfhwAs9ZhXqMuP76wls82hDFZe1FDJPpm6mweBZY9wiEgBVk8Xkkz+bcGEAeQyPDFGxdIZv64dW89yZq2fePnufu+KTdegIuh9zGdkf8P9VnAy7nNvzk9vgDNQbBvujz5KMZEds3K+8yBgII63XHt5F7VQevLGpKmUWMb+ejfTp3fujsL/mXMJXshQKguK/+CTgsNee6RPXTZQ4PIwG0IJjNLYjBIzVgCUxy6Njcq3lvEurXEA352Zp0GbcMWlMyVp2GkBst5pLqOfNir3GOux5G0WJtbHdZaUMy6BeXSJXIuBODBYyVIXh44lTiglqb+kwkZKR5KKjnBX7oGRP72td5Yzkl18Ds3FoaOsFLvrRcAySIp+f5OLXQHWR0W3KjFsYqjRFx0KrcEEsk/NX2Gd/p0n5Z/pU7R2XxSHsfnqsYtcdJrozEYAEk/i8mmO2EqKS4R+tH8BWqMr1vUWVVNxxNoYMP8oTHiW2X/crYDQPCGMVYZ5sKuq/hopOBrUochX4++FM=
appveyor:
  secure:
    BINSTAR_TOKEN: OcAUZlpSDgQtX8QAIX7qr8iZhsrOWwlmuyDECE7wAYBRlvXIBJ7BbXhX/Fmz4Oib

channels:
  sources: [cryoem, defaults, conda-forge]
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: eman-dependencies-feedstock
