travis:
  secure:
    BINSTAR_TOKEN: XUi4O2kWQz9Qo3B3RLOiP+LYXvT/l4+I4cKPTiwtsVFyxRxPAwV5IHYWycwQ1XrGl/zZEnBDFHxzTzJQVH3hwL5MS51F1iVI7yeoDdFtJQ8SHMyDUP/wjktohcAtqIzSMuN4faoqFF3ziwlcLYCez1cMNHB4Qlgx/8J8PfEvCrLWvnFeFWi4SP3S6hXcSyqEhjbJhl7UohRWHYr9fxgb7j3xetDgNS5w8lTcXn9QxKrk0lSNqCOCI2FFanvEJhm5Zbi1l9olG8A9g4dlBF8BP0Sk7z1BYfysptrDvxczs6ZAQI6tT0sQ+Ki6hrsp1s6hA1TDUDfJ7c81V3QAxLNMkyNXw00/wi3dd4j0OL3WVFnkN5pcOsWUKfovMZA8dbOGD//FZdoCXKF2zwNYHprZiceqCR5yf141eL56zhl2Nmwlxp2cCbaFwzMKq0gL46ZJJa0Uj8KzREurSwS+DN88lzXplZgSKOIJJXH5kIcdnL0jo2HC8ZzjuQZMz1SwlJUgVwYzLz9JSFi6UaBwRu+wKRn8tRf+IbmkMiO5uFOJniBMwyfRzRmzaUtfwbFJDNr7qmLUDDCj/UBRVTCfankV62VhXYpDsawRcEJyaEbHjiY6SfUWwZdMD7oxu14TkMhhu26Jzbfr4ITzqOl9h1dONZFcmxFCIdC54bXABXpHy4s=
appveyor:
  secure:
    BINSTAR_TOKEN: OcAUZlpSDgQtX8QAIX7qr8iZhsrOWwlmuyDECE7wAYBRlvXIBJ7BbXhX/Fmz4Oib

channels:
  sources: [cryoem, defaults, conda-forge]
  targets:
  - [cryoem, dev]

github:
  user_or_org: cryoem
  repo_name: eman-deps-feedstock
